name: default pipeline

on:
  #allows workflow to be triggered manually
  workflow_call:

  #runs on all push requests
  push:
  pull_request:
    branches:
      - main
      - master

env:
  #sets the default node version for the workflow
  PACKAGE_PATH: 'typescript/'
  NODE_VERSION: '22.x'

jobs:
  prepare_variables:
    runs-on: ubuntu-latest
    outputs:
      package-path: ${{ env.PACKAGE_PATH }}
      node-version: ${{ env.NODE_VERSION }}
    steps:
      - run: echo "Preparing env vars via outputs"

  build_dev_call_from_local_repo:
    needs: prepare_variables
    uses: ./.github/workflows/node-build.yml
    with:
      package-path: "$PACKAGE_PATH"
      node-version: "$NODE_VERSION"

  build_dev_call_from_another_repo:
    needs: prepare_variables
    uses: leroyleejh/base-ci/.github/workflows/node-build.yml@main
    with:
      package-path: ${{ needs.prepare_variables.outputs.package-path }}
      node-version: ${{ needs.prepare_variables.outputs.node-version }}