name: default pipeline

on:
  #allows workflow to be triggered manually
  workflow_call:

  #runs on all push requests
  push:
  pull_request:
    branches:
      - main
      - master

env:
  #sets the default node version for the workflow
  PACKAGE_PATH: 'typescript/'
  NODE_VERSION: '22.x'

jobs:
  build_dev_call_from_local_repo:
    uses: ./.github/workflows/node-build.yml
    with:
      package-path: "$PACKAGE_PATH"
      node-version: "$NODE_VERSION"

  build_dev_call_from_another_repo:
    uses: leroyleejh/base-ci/.github/workflows/node-build.yml@main
    with:
      package-path: "$PACKAGE_PATH"
      node-version: "$NODE_VERSION"