name: deafault pipeline

on:
  #allows workflow to be triggered manually
  workflow_call:

  #runs on all push requests
  push:
  pull_request:
    branches:
      - main
      - master

env:
  #sets the default node version for the workflow
  package-path: 'typescript/'
  node-version: '22.x'

jobs:
  build_dev:
    uses: ./.github/actions/node-build
    with:
      package-path: ${{ env.package-path }}
      node-version: ${{ env.node-version }}
