name: node-test

on:
  workflow_call:
    inputs:
      package-path:
        required: true
        type: string
        default: '.'
      node-version:
        required: true
        type: string
        default: '22.x'
      test-command:
        required: true
        type: string
        default: 'npm run test'

jobs:
  build_dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: ${{ inputs.package-path }}
    - name: install npm dependencies
      run: cd ${{ inputs.package-path }} && NODE_ENV=build && npm ci
    - name: run test
      run: cd ${{ inputs.package-path } && ${{ inputs.test-command }}
